# Generated by Django 4.0.3 on 2022-04-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('round', models.IntegerField()),
                ('circuit_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('points', models.FloatField()),
                ('driver_id', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('true_time', models.CharField(max_length=100)),
            ],
        ),
    ]
