# Generated by Django 4.0.4 on 2022-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_driver_standing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100)),
                ('permanentNumber', models.IntegerField()),
                ('givenName', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
    ]
