# Generated by Django 4.0.4 on 2022-04-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_constructor_constructor_standing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor_standing',
            name='team_name',
        ),
    ]
